#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define GAME_TITLE "Homem-Aranha Subindo o Predio"

#define PLAYER_WIDTH 50
#define PLAYER_HEIGHT 70
#define PLAYER_SPEED 300.0f

#define OBSTACLE_WIDTH 50
#define OBSTACLE_HEIGHT 50
#define OBSTACLE_SPEED 350.0f

#define BUILDING_X 250
#define BUILDING_WIDTH 300

#define LANE_COUNT 3
#define LANE_WIDTH (BUILDING_WIDTH / LANE_COUNT)

#endif