#ifndef CONFIG_H
#define CONFIG_H

#define LARGURA_TELA 800
#define ALTURA_TELA 600

#define TITULO_JOGO "Amazing Climb"

#define LARGURA_JOGADOR 50
#define ALTURA_JOGADOR 70
#define VIDAS_INICIAIS 3
#define FAIXA_INICIAL_JOGADOR 1
#define MARGEM_INFERIOR_JOGADOR 120
#define TEMPO_ANIMACAO_JOGADOR 0.2f

#define LARGURA_OBSTACULO 80
#define ALTURA_OBSTACULO 80
#define VELOCIDADE_OBSTACULO 350.0f
#define QTD_TEXTURAS_OBSTACULOS 3
#define MIN_OBSTACULOS_SPAWN 1
#define MAX_OBSTACULOS_SPAWN 2

#define PREDIO_X 250
#define LARGURA_PREDIO 300

#define QTD_FAIXAS 3
#define LARGURA_FAIXA (LARGURA_PREDIO / QTD_FAIXAS)

#define TOTAL_FRAMES_FUNDO 10
#define TEMPO_FRAME_FUNDO 0.1f
#define VELOCIDADE_FUNDO 120.0f

#define INTERVALO_SPAWN 1.0f
#define TEMPO_INVENCIBILIDADE 1.0f

#define ESPACO_JANELAS 90
#define TAMANHO_JANELA 55
#define TAMANHO_SPRITE_JANELA 208
#define QTD_TIPOS_JANELA 4

#endif
